name: gitpod_dart
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/DanTup/gitpod-dart
author: Danny Tuppeny <danny@tuppeny.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
